# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

repos:
  # pylint/ruff sync
  - repo: https://github.com/cidrblock/pylint-ruff-sync
    rev: v25.07.18.000003
    hooks:
      - id: pylint-ruff-sync

  # uv
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.11
    hooks:
      - id: uv-lock

  # Google
  - repo: https://github.com/google/pre-commit-tool-hooks
    rev: v1.2.5
    hooks:
      - id: check-copyright
        args:
          - --custom_format
          - '\.py$'
          - ""
          - "# "
          - ""
          - --custom_format
          - '\.sql$'
          - ""
          - "-- "
          - ""
          - --skip_pattern
          - .*\.md|.*\.config\.js|\.pylintrc|LICENSE|.*\.toml|\.gitignore|\.git|requirements\.txt|google-ads.yaml|uv.lock|.python-version
      - id: check-google-doc-style
      - id: check-links

  # Miscellaneous
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # Python
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.8
    hooks:
      - id: pylint
  - repo: https://github.com/google/pytype
    rev: 2024.10.11
    hooks:
      - id: pytype
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.403
    hooks:
      - id: pyright
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format
  - repo: local
    hooks:
      - id: python-testing
        name: Running Python tests
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        types:
          - python

  # Markdown
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-config
          - mdformat-footnote
          - mdformat-frontmatter
          - mdformat-gfm
          - mdformat-gfm-alerts
          - mdformat-ruff
          - mdformat-shfmt

  # Conventional Commits
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen

  # SQL
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.2
    hooks:
      - id: sqlfluff-lint
        additional_dependencies:
          - dbt-bigquery
      - id: sqlfluff-fix
        additional_dependencies:
          - dbt-bigquery
