name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: ".pre-commit-config.yaml"
      - run: uv sync --group dev
      - run: uv run --isolated --no-sync true && echo "pythonLocation=$(uv python find)" >> $GITHUB_ENV
        shell: bash
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: uv run --no-sync --with pre-commit-uv pre-commit run --show-diff-on-failure --color=always --all-files
        shell: bash
